#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 151
#define LARGE_STATE_COUNT 22
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  sym_recur = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_DOT_DOT_DOT = 4,
  anon_sym_begin = 5,
  anon_sym_defn = 6,
  anon_sym_fn = 7,
  anon_sym_cond = 8,
  anon_sym_else = 9,
  anon_sym_def = 10,
  anon_sym_set = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  sym_ident = 16,
  sym_number = 17,
  sym_float = 18,
  anon_sym_DQUOTE = 19,
  aux_sym_string_token1 = 20,
  sym_string_escape = 21,
  sym_true = 22,
  sym_false = 23,
  aux_sym_comment_token1 = 24,
  sym_source_file = 25,
  sym__expr = 26,
  sym_list = 27,
  sym_splat = 28,
  sym_begin = 29,
  sym_defn = 30,
  sym_fn = 31,
  sym__func_inner = 32,
  sym_multifn = 33,
  sym_multifn_inner = 34,
  sym__fn_inner = 35,
  sym_cond = 36,
  sym__cond_inner = 37,
  sym_cond_else = 38,
  sym_cond_branch = 39,
  sym_def = 40,
  sym_set = 41,
  sym_vector = 42,
  sym_squiggle = 43,
  sym_string = 44,
  sym_comment = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_multifn_repeat1 = 47,
  aux_sym_cond_repeat1 = 48,
  aux_sym_vector_repeat1 = 49,
  aux_sym_string_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_recur] = "recur",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_begin] = "begin",
  [anon_sym_defn] = "defn",
  [anon_sym_fn] = "fn",
  [anon_sym_cond] = "cond",
  [anon_sym_else] = "else",
  [anon_sym_def] = "def",
  [anon_sym_set] = "set",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_ident] = "ident",
  [sym_number] = "number",
  [sym_float] = "float",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_string_escape] = "string_escape",
  [sym_true] = "true",
  [sym_false] = "false",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_list] = "list",
  [sym_splat] = "splat",
  [sym_begin] = "begin",
  [sym_defn] = "defn",
  [sym_fn] = "fn",
  [sym__func_inner] = "_func_inner",
  [sym_multifn] = "multifn",
  [sym_multifn_inner] = "multifn_inner",
  [sym__fn_inner] = "_fn_inner",
  [sym_cond] = "cond",
  [sym__cond_inner] = "_cond_inner",
  [sym_cond_else] = "cond_else",
  [sym_cond_branch] = "cond_branch",
  [sym_def] = "def",
  [sym_set] = "set",
  [sym_vector] = "vector",
  [sym_squiggle] = "squiggle",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_multifn_repeat1] = "multifn_repeat1",
  [aux_sym_cond_repeat1] = "cond_repeat1",
  [aux_sym_vector_repeat1] = "vector_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_recur] = sym_recur,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_begin] = anon_sym_begin,
  [anon_sym_defn] = anon_sym_defn,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_cond] = anon_sym_cond,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_ident] = sym_ident,
  [sym_number] = sym_number,
  [sym_float] = sym_float,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_string_escape] = sym_string_escape,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_list] = sym_list,
  [sym_splat] = sym_splat,
  [sym_begin] = sym_begin,
  [sym_defn] = sym_defn,
  [sym_fn] = sym_fn,
  [sym__func_inner] = sym__func_inner,
  [sym_multifn] = sym_multifn,
  [sym_multifn_inner] = sym_multifn_inner,
  [sym__fn_inner] = sym__fn_inner,
  [sym_cond] = sym_cond,
  [sym__cond_inner] = sym__cond_inner,
  [sym_cond_else] = sym_cond_else,
  [sym_cond_branch] = sym_cond_branch,
  [sym_def] = sym_def,
  [sym_set] = sym_set,
  [sym_vector] = sym_vector,
  [sym_squiggle] = sym_squiggle,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_multifn_repeat1] = aux_sym_multifn_repeat1,
  [aux_sym_cond_repeat1] = aux_sym_cond_repeat1,
  [aux_sym_vector_repeat1] = aux_sym_vector_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_recur] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_begin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cond] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_splat] = {
    .visible = true,
    .named = true,
  },
  [sym_begin] = {
    .visible = true,
    .named = true,
  },
  [sym_defn] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym__func_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_multifn] = {
    .visible = true,
    .named = true,
  },
  [sym_multifn_inner] = {
    .visible = true,
    .named = true,
  },
  [sym__fn_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_cond] = {
    .visible = true,
    .named = true,
  },
  [sym__cond_inner] = {
    .visible = false,
    .named = true,
  },
  [sym_cond_else] = {
    .visible = true,
    .named = true,
  },
  [sym_cond_branch] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym_squiggle] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multifn_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cond_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_first = 2,
  field_keyword = 3,
  field_name = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_first] = "first",
  [field_keyword] = "keyword",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 1},
  [1] =
    {field_first, 1},
  [2] =
    {field_name, 2},
  [3] =
    {field_condition, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 2,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 6,
  [13] = 5,
  [14] = 14,
  [15] = 11,
  [16] = 6,
  [17] = 14,
  [18] = 5,
  [19] = 19,
  [20] = 14,
  [21] = 11,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 23,
  [26] = 26,
  [27] = 24,
  [28] = 23,
  [29] = 29,
  [30] = 30,
  [31] = 24,
  [32] = 29,
  [33] = 29,
  [34] = 34,
  [35] = 34,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 39,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 54,
  [56] = 53,
  [57] = 57,
  [58] = 47,
  [59] = 59,
  [60] = 46,
  [61] = 52,
  [62] = 50,
  [63] = 45,
  [64] = 42,
  [65] = 43,
  [66] = 48,
  [67] = 44,
  [68] = 57,
  [69] = 41,
  [70] = 40,
  [71] = 51,
  [72] = 72,
  [73] = 73,
  [74] = 73,
  [75] = 72,
  [76] = 73,
  [77] = 72,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 80,
  [83] = 79,
  [84] = 80,
  [85] = 79,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 86,
  [91] = 36,
  [92] = 88,
  [93] = 34,
  [94] = 86,
  [95] = 88,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 97,
  [101] = 101,
  [102] = 97,
  [103] = 46,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 43,
  [109] = 50,
  [110] = 41,
  [111] = 45,
  [112] = 42,
  [113] = 113,
  [114] = 114,
  [115] = 51,
  [116] = 114,
  [117] = 40,
  [118] = 113,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 47,
  [123] = 44,
  [124] = 124,
  [125] = 48,
  [126] = 126,
  [127] = 113,
  [128] = 128,
  [129] = 57,
  [130] = 130,
  [131] = 114,
  [132] = 52,
  [133] = 121,
  [134] = 119,
  [135] = 120,
  [136] = 121,
  [137] = 120,
  [138] = 138,
  [139] = 139,
  [140] = 54,
  [141] = 53,
  [142] = 119,
  [143] = 143,
  [144] = 39,
  [145] = 139,
  [146] = 126,
  [147] = 124,
  [148] = 139,
  [149] = 126,
  [150] = 124,
};

static TSCharacterRange sym_ident_character_set_1[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'$', '&'}, {'*', '/'}, {':', 'Z'}, {'\\', '\\'},
  {'^', '_'}, {'a', 'z'}, {'|', '|'}, {0x7f, 0x10ffff},
};

static TSCharacterRange sym_ident_character_set_3[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'#', '\''}, {'*', '-'}, {'/', 'Z'}, {'\\', '\\'},
  {'^', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '"', 84,
        '#', 14,
        '(', 33,
        ')', 34,
        '.', 5,
        ';', 92,
        '[', 50,
        '\\', 27,
        ']', 51,
        'b', 9,
        'c', 22,
        'd', 10,
        'e', 18,
        'f', 19,
        'r', 11,
        's', 12,
        '{', 52,
        '}', 53,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 84,
        '#', 14,
        '(', 33,
        ')', 34,
        '.', 59,
        ';', 80,
        '[', 50,
        'b', 63,
        'c', 75,
        'd', 64,
        'f', 72,
        'r', 62,
        's', 65,
        0x0b, 54,
        '\f', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(81);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 84,
        '#', 14,
        '(', 33,
        '.', 59,
        ';', 80,
        'e', 71,
        'r', 62,
        0x0b, 55,
        '\f', 55,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(81);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if (lookahead != 0) ADVANCE(85);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == ']') ADVANCE(51);
      if (lookahead == '}') ADVANCE(53);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if ((!eof && set_contains(sym_ident_character_set_1, 12, lookahead))) ADVANCE(81);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(90);
      if (lookahead == 't') ADVANCE(88);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(46);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 27:
      if (lookahead == '"' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(87);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '"', 84,
        '#', 14,
        '(', 33,
        ')', 34,
        '.', 59,
        ';', 80,
        'r', 62,
        0x0b, 56,
        '\f', 56,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}' &&
          lookahead != '~') ADVANCE(81);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_recur);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_recur);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_begin);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_begin);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_defn);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_defn);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_fn);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_cond);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_cond);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_else);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == 'n') ADVANCE(39);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_set);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ident);
      ADVANCE_MAP(
        '#', 67,
        '.', 59,
        ';', 80,
        'b', 63,
        'c', 75,
        'd', 64,
        'f', 72,
        'r', 62,
        's', 65,
        0x0b, 54,
        '\f', 54,
        '\'', 81,
        '`', 81,
        '~', 81,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ident);
      ADVANCE_MAP(
        '#', 67,
        '.', 59,
        ';', 80,
        'e', 71,
        'r', 62,
        0x0b, 55,
        '\f', 55,
        '\'', 81,
        '`', 81,
        '~', 81,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ident);
      ADVANCE_MAP(
        '#', 67,
        '.', 59,
        ';', 80,
        'r', 62,
        0x0b, 56,
        '\f', 56,
        '\'', 81,
        '`', 81,
        '~', 81,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(57);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '.') ADVANCE(81);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(58);
      if (lookahead == '#' ||
          lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '`' ||
          lookahead == '~') ADVANCE(81);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '.') ADVANCE(4);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'c') ADVANCE(79);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'd') ADVANCE(43);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(60);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(69);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(68);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(78);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(45);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'f') ADVANCE(91);
      if (lookahead == 't') ADVANCE(89);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'f') ADVANCE(47);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'g') ADVANCE(70);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(74);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(77);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(41);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(61);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(37);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(73);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(32);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(66);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(49);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(76);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_ident);
      ADVANCE_MAP(
        '\t', 92,
        '\r', 92,
        ' ', 92,
        '"', 92,
        '(', 92,
        ')', 92,
        '.', 92,
        '[', 92,
        ']', 92,
        '{', 92,
        '}', 92,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_ident);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_string_escape);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_true);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_false);
      if ((!eof && set_contains(sym_ident_character_set_3, 11, lookahead))) ADVANCE(81);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(92);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 29},
  [6] = {.lex_state = 29},
  [7] = {.lex_state = 29},
  [8] = {.lex_state = 29},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 29},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 29},
  [13] = {.lex_state = 29},
  [14] = {.lex_state = 29},
  [15] = {.lex_state = 29},
  [16] = {.lex_state = 29},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 29},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 29},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 29},
  [26] = {.lex_state = 29},
  [27] = {.lex_state = 29},
  [28] = {.lex_state = 29},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 29},
  [31] = {.lex_state = 29},
  [32] = {.lex_state = 29},
  [33] = {.lex_state = 29},
  [34] = {.lex_state = 29},
  [35] = {.lex_state = 29},
  [36] = {.lex_state = 29},
  [37] = {.lex_state = 29},
  [38] = {.lex_state = 29},
  [39] = {.lex_state = 29},
  [40] = {.lex_state = 29},
  [41] = {.lex_state = 29},
  [42] = {.lex_state = 29},
  [43] = {.lex_state = 29},
  [44] = {.lex_state = 29},
  [45] = {.lex_state = 29},
  [46] = {.lex_state = 29},
  [47] = {.lex_state = 29},
  [48] = {.lex_state = 29},
  [49] = {.lex_state = 29},
  [50] = {.lex_state = 29},
  [51] = {.lex_state = 29},
  [52] = {.lex_state = 29},
  [53] = {.lex_state = 29},
  [54] = {.lex_state = 29},
  [55] = {.lex_state = 29},
  [56] = {.lex_state = 29},
  [57] = {.lex_state = 29},
  [58] = {.lex_state = 29},
  [59] = {.lex_state = 29},
  [60] = {.lex_state = 29},
  [61] = {.lex_state = 29},
  [62] = {.lex_state = 29},
  [63] = {.lex_state = 29},
  [64] = {.lex_state = 29},
  [65] = {.lex_state = 29},
  [66] = {.lex_state = 29},
  [67] = {.lex_state = 29},
  [68] = {.lex_state = 29},
  [69] = {.lex_state = 29},
  [70] = {.lex_state = 29},
  [71] = {.lex_state = 29},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 6},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 6},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 6},
  [99] = {.lex_state = 6},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 6},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 6},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 6},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 6},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 6},
  [146] = {.lex_state = 6},
  [147] = {.lex_state = 6},
  [148] = {.lex_state = 6},
  [149] = {.lex_state = 6},
  [150] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_recur] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_begin] = ACTIONS(1),
    [anon_sym_defn] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_cond] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_string_escape] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(143),
    [sym__expr] = STATE(8),
    [sym_list] = STATE(8),
    [sym_splat] = STATE(8),
    [sym_begin] = STATE(8),
    [sym_defn] = STATE(8),
    [sym_fn] = STATE(8),
    [sym_multifn] = STATE(8),
    [sym_multifn_inner] = STATE(36),
    [sym_cond] = STATE(8),
    [sym_def] = STATE(8),
    [sym_set] = STATE(8),
    [sym_string] = STATE(8),
    [sym_comment] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_multifn_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_recur] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(9),
    [sym_ident] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [sym_float] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_true] = ACTIONS(5),
    [sym_false] = ACTIONS(5),
    [aux_sym_comment_token1] = ACTIONS(13),
  },
  [2] = {
    [sym__expr] = STATE(14),
    [sym_list] = STATE(14),
    [sym_splat] = STATE(14),
    [sym_begin] = STATE(14),
    [sym_defn] = STATE(14),
    [sym_fn] = STATE(14),
    [sym_multifn] = STATE(14),
    [sym_multifn_inner] = STATE(37),
    [sym__fn_inner] = STATE(127),
    [sym_cond] = STATE(14),
    [sym_def] = STATE(14),
    [sym_set] = STATE(14),
    [sym_vector] = STATE(19),
    [sym_string] = STATE(14),
    [sym_comment] = STATE(14),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(19),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [anon_sym_begin] = ACTIONS(23),
    [anon_sym_defn] = ACTIONS(25),
    [anon_sym_fn] = ACTIONS(27),
    [anon_sym_cond] = ACTIONS(29),
    [anon_sym_def] = ACTIONS(31),
    [anon_sym_set] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
    [sym_ident] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [sym_float] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(15),
    [sym_false] = ACTIONS(15),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [3] = {
    [sym__expr] = STATE(17),
    [sym_list] = STATE(17),
    [sym_splat] = STATE(17),
    [sym_begin] = STATE(17),
    [sym_defn] = STATE(17),
    [sym_fn] = STATE(17),
    [sym_multifn] = STATE(17),
    [sym_multifn_inner] = STATE(37),
    [sym__fn_inner] = STATE(118),
    [sym_cond] = STATE(17),
    [sym_def] = STATE(17),
    [sym_set] = STATE(17),
    [sym_vector] = STATE(19),
    [sym_string] = STATE(17),
    [sym_comment] = STATE(17),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [anon_sym_begin] = ACTIONS(45),
    [anon_sym_defn] = ACTIONS(47),
    [anon_sym_fn] = ACTIONS(49),
    [anon_sym_cond] = ACTIONS(51),
    [anon_sym_def] = ACTIONS(53),
    [anon_sym_set] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(35),
    [sym_ident] = ACTIONS(41),
    [sym_number] = ACTIONS(41),
    [sym_float] = ACTIONS(41),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(41),
    [sym_false] = ACTIONS(41),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [4] = {
    [sym__expr] = STATE(20),
    [sym_list] = STATE(20),
    [sym_splat] = STATE(20),
    [sym_begin] = STATE(20),
    [sym_defn] = STATE(20),
    [sym_fn] = STATE(20),
    [sym_multifn] = STATE(20),
    [sym_multifn_inner] = STATE(37),
    [sym__fn_inner] = STATE(113),
    [sym_cond] = STATE(20),
    [sym_def] = STATE(20),
    [sym_set] = STATE(20),
    [sym_vector] = STATE(19),
    [sym_string] = STATE(20),
    [sym_comment] = STATE(20),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [anon_sym_begin] = ACTIONS(61),
    [anon_sym_defn] = ACTIONS(63),
    [anon_sym_fn] = ACTIONS(65),
    [anon_sym_cond] = ACTIONS(67),
    [anon_sym_def] = ACTIONS(69),
    [anon_sym_set] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(35),
    [sym_ident] = ACTIONS(57),
    [sym_number] = ACTIONS(57),
    [sym_float] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(57),
    [sym_false] = ACTIONS(57),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [5] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_splat] = STATE(9),
    [sym_begin] = STATE(9),
    [sym_defn] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_multifn] = STATE(9),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(9),
    [sym_def] = STATE(9),
    [sym_set] = STATE(9),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [sym_float] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(73),
    [sym_false] = ACTIONS(73),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [6] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_splat] = STATE(9),
    [sym_begin] = STATE(9),
    [sym_defn] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_multifn] = STATE(9),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(9),
    [sym_def] = STATE(9),
    [sym_set] = STATE(9),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [sym_float] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(73),
    [sym_false] = ACTIONS(73),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [7] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_splat] = STATE(9),
    [sym_begin] = STATE(9),
    [sym_defn] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_multifn] = STATE(9),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(9),
    [sym_def] = STATE(9),
    [sym_set] = STATE(9),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [sym_float] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(73),
    [sym_false] = ACTIONS(73),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [8] = {
    [sym__expr] = STATE(10),
    [sym_list] = STATE(10),
    [sym_splat] = STATE(10),
    [sym_begin] = STATE(10),
    [sym_defn] = STATE(10),
    [sym_fn] = STATE(10),
    [sym_multifn] = STATE(10),
    [sym_multifn_inner] = STATE(36),
    [sym_cond] = STATE(10),
    [sym_def] = STATE(10),
    [sym_set] = STATE(10),
    [sym_string] = STATE(10),
    [sym_comment] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_multifn_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_recur] = ACTIONS(83),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(9),
    [sym_ident] = ACTIONS(83),
    [sym_number] = ACTIONS(83),
    [sym_float] = ACTIONS(83),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_true] = ACTIONS(83),
    [sym_false] = ACTIONS(83),
    [aux_sym_comment_token1] = ACTIONS(13),
  },
  [9] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_splat] = STATE(9),
    [sym_begin] = STATE(9),
    [sym_defn] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_multifn] = STATE(9),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(9),
    [sym_def] = STATE(9),
    [sym_set] = STATE(9),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(88),
    [anon_sym_RPAREN] = ACTIONS(91),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(93),
    [sym_ident] = ACTIONS(85),
    [sym_number] = ACTIONS(85),
    [sym_float] = ACTIONS(85),
    [anon_sym_DQUOTE] = ACTIONS(96),
    [sym_true] = ACTIONS(85),
    [sym_false] = ACTIONS(85),
    [aux_sym_comment_token1] = ACTIONS(99),
  },
  [10] = {
    [sym__expr] = STATE(10),
    [sym_list] = STATE(10),
    [sym_splat] = STATE(10),
    [sym_begin] = STATE(10),
    [sym_defn] = STATE(10),
    [sym_fn] = STATE(10),
    [sym_multifn] = STATE(10),
    [sym_multifn_inner] = STATE(36),
    [sym_cond] = STATE(10),
    [sym_def] = STATE(10),
    [sym_set] = STATE(10),
    [sym_string] = STATE(10),
    [sym_comment] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_multifn_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(102),
    [sym_recur] = ACTIONS(104),
    [anon_sym_LPAREN] = ACTIONS(107),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(110),
    [sym_ident] = ACTIONS(104),
    [sym_number] = ACTIONS(104),
    [sym_float] = ACTIONS(104),
    [anon_sym_DQUOTE] = ACTIONS(113),
    [sym_true] = ACTIONS(104),
    [sym_false] = ACTIONS(104),
    [aux_sym_comment_token1] = ACTIONS(116),
  },
  [11] = {
    [sym__expr] = STATE(5),
    [sym_list] = STATE(5),
    [sym_splat] = STATE(5),
    [sym_begin] = STATE(5),
    [sym_defn] = STATE(5),
    [sym_fn] = STATE(5),
    [sym_multifn] = STATE(5),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(5),
    [sym_def] = STATE(5),
    [sym_set] = STATE(5),
    [sym_string] = STATE(5),
    [sym_comment] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(121),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(119),
    [sym_number] = ACTIONS(119),
    [sym_float] = ACTIONS(119),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(119),
    [sym_false] = ACTIONS(119),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [12] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_splat] = STATE(9),
    [sym_begin] = STATE(9),
    [sym_defn] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_multifn] = STATE(9),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(9),
    [sym_def] = STATE(9),
    [sym_set] = STATE(9),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(123),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [sym_float] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(73),
    [sym_false] = ACTIONS(73),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [13] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_splat] = STATE(9),
    [sym_begin] = STATE(9),
    [sym_defn] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_multifn] = STATE(9),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(9),
    [sym_def] = STATE(9),
    [sym_set] = STATE(9),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(125),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [sym_float] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(73),
    [sym_false] = ACTIONS(73),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [14] = {
    [sym__expr] = STATE(12),
    [sym_list] = STATE(12),
    [sym_splat] = STATE(12),
    [sym_begin] = STATE(12),
    [sym_defn] = STATE(12),
    [sym_fn] = STATE(12),
    [sym_multifn] = STATE(12),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(12),
    [sym_def] = STATE(12),
    [sym_set] = STATE(12),
    [sym_string] = STATE(12),
    [sym_comment] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(127),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(129),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(127),
    [sym_number] = ACTIONS(127),
    [sym_float] = ACTIONS(127),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(127),
    [sym_false] = ACTIONS(127),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [15] = {
    [sym__expr] = STATE(13),
    [sym_list] = STATE(13),
    [sym_splat] = STATE(13),
    [sym_begin] = STATE(13),
    [sym_defn] = STATE(13),
    [sym_fn] = STATE(13),
    [sym_multifn] = STATE(13),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(13),
    [sym_def] = STATE(13),
    [sym_set] = STATE(13),
    [sym_string] = STATE(13),
    [sym_comment] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(131),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(133),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(131),
    [sym_number] = ACTIONS(131),
    [sym_float] = ACTIONS(131),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(131),
    [sym_false] = ACTIONS(131),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [16] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_splat] = STATE(9),
    [sym_begin] = STATE(9),
    [sym_defn] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_multifn] = STATE(9),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(9),
    [sym_def] = STATE(9),
    [sym_set] = STATE(9),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(135),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [sym_float] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(73),
    [sym_false] = ACTIONS(73),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [17] = {
    [sym__expr] = STATE(6),
    [sym_list] = STATE(6),
    [sym_splat] = STATE(6),
    [sym_begin] = STATE(6),
    [sym_defn] = STATE(6),
    [sym_fn] = STATE(6),
    [sym_multifn] = STATE(6),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(6),
    [sym_def] = STATE(6),
    [sym_set] = STATE(6),
    [sym_string] = STATE(6),
    [sym_comment] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(139),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(137),
    [sym_number] = ACTIONS(137),
    [sym_float] = ACTIONS(137),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(137),
    [sym_false] = ACTIONS(137),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [18] = {
    [sym__expr] = STATE(9),
    [sym_list] = STATE(9),
    [sym_splat] = STATE(9),
    [sym_begin] = STATE(9),
    [sym_defn] = STATE(9),
    [sym_fn] = STATE(9),
    [sym_multifn] = STATE(9),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(9),
    [sym_def] = STATE(9),
    [sym_set] = STATE(9),
    [sym_string] = STATE(9),
    [sym_comment] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(141),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [sym_float] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(73),
    [sym_false] = ACTIONS(73),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [19] = {
    [sym__expr] = STATE(7),
    [sym_list] = STATE(7),
    [sym_splat] = STATE(7),
    [sym_begin] = STATE(7),
    [sym_defn] = STATE(7),
    [sym_fn] = STATE(7),
    [sym_multifn] = STATE(7),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(7),
    [sym_def] = STATE(7),
    [sym_set] = STATE(7),
    [sym_string] = STATE(7),
    [sym_comment] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(143),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(145),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(143),
    [sym_number] = ACTIONS(143),
    [sym_float] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(143),
    [sym_false] = ACTIONS(143),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [20] = {
    [sym__expr] = STATE(16),
    [sym_list] = STATE(16),
    [sym_splat] = STATE(16),
    [sym_begin] = STATE(16),
    [sym_defn] = STATE(16),
    [sym_fn] = STATE(16),
    [sym_multifn] = STATE(16),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(16),
    [sym_def] = STATE(16),
    [sym_set] = STATE(16),
    [sym_string] = STATE(16),
    [sym_comment] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(149),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(147),
    [sym_number] = ACTIONS(147),
    [sym_float] = ACTIONS(147),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(147),
    [sym_false] = ACTIONS(147),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
  [21] = {
    [sym__expr] = STATE(18),
    [sym_list] = STATE(18),
    [sym_splat] = STATE(18),
    [sym_begin] = STATE(18),
    [sym_defn] = STATE(18),
    [sym_fn] = STATE(18),
    [sym_multifn] = STATE(18),
    [sym_multifn_inner] = STATE(37),
    [sym_cond] = STATE(18),
    [sym_def] = STATE(18),
    [sym_set] = STATE(18),
    [sym_string] = STATE(18),
    [sym_comment] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(18),
    [aux_sym_multifn_repeat1] = STATE(37),
    [sym_recur] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_RPAREN] = ACTIONS(153),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(21),
    [sym_ident] = ACTIONS(151),
    [sym_number] = ACTIONS(151),
    [sym_float] = ACTIONS(151),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [sym_true] = ACTIONS(151),
    [sym_false] = ACTIONS(151),
    [aux_sym_comment_token1] = ACTIONS(39),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      aux_sym_comment_token1,
    ACTIONS(157), 1,
      anon_sym_else,
    STATE(37), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(155), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(26), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [42] = 7,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_comment_token1,
    STATE(36), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(159), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(41), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [81] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(161), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(120), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [120] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(171), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(110), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [159] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(173), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(128), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [198] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(175), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(135), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [237] = 7,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      aux_sym_comment_token1,
    STATE(37), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(177), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(69), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [276] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(179), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(121), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [315] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(181), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(130), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [354] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(183), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(137), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [393] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(185), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(133), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [432] = 7,
    ACTIONS(163), 1,
      anon_sym_LPAREN,
    ACTIONS(165), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_comment_token1,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(187), 6,
      sym_recur,
      sym_ident,
      sym_number,
      sym_float,
      sym_true,
      sym_false,
    STATE(136), 12,
      sym__expr,
      sym_list,
      sym_splat,
      sym_begin,
      sym_defn,
      sym_fn,
      sym_multifn,
      sym_cond,
      sym_def,
      sym_set,
      sym_string,
      sym_comment,
  [471] = 4,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    ACTIONS(193), 1,
      anon_sym_LPAREN,
    STATE(34), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(191), 9,
      sym_recur,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [493] = 3,
    ACTIONS(196), 1,
      anon_sym_LPAREN,
    STATE(35), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(191), 10,
      sym_recur,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [513] = 3,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    STATE(34), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(201), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [533] = 2,
    STATE(35), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    ACTIONS(201), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [551] = 1,
    ACTIONS(203), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [565] = 1,
    ACTIONS(205), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [579] = 2,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    ACTIONS(209), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [595] = 2,
    ACTIONS(211), 1,
      ts_builtin_sym_end,
    ACTIONS(213), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [611] = 2,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
    ACTIONS(217), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [627] = 2,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    ACTIONS(221), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [643] = 1,
    ACTIONS(223), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [657] = 2,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
    ACTIONS(227), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [673] = 2,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
    ACTIONS(231), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [689] = 2,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
    ACTIONS(235), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [705] = 1,
    ACTIONS(237), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [719] = 2,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [735] = 1,
    ACTIONS(241), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [749] = 2,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
    ACTIONS(245), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [765] = 1,
    ACTIONS(247), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [779] = 2,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    ACTIONS(251), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [795] = 1,
    ACTIONS(253), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [809] = 2,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
    ACTIONS(253), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [825] = 1,
    ACTIONS(251), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [839] = 2,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
    ACTIONS(259), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [855] = 1,
    ACTIONS(235), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [869] = 1,
    ACTIONS(261), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [883] = 1,
    ACTIONS(231), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [897] = 2,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [913] = 2,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
    ACTIONS(241), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [929] = 1,
    ACTIONS(227), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [943] = 1,
    ACTIONS(217), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [957] = 1,
    ACTIONS(221), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [971] = 2,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
    ACTIONS(237), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [987] = 2,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
    ACTIONS(223), 10,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [1003] = 1,
    ACTIONS(259), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [1017] = 1,
    ACTIONS(213), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [1031] = 1,
    ACTIONS(209), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [1045] = 1,
    ACTIONS(245), 11,
      sym_recur,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_DOT_DOT_DOT,
      sym_ident,
      sym_number,
      sym_float,
      anon_sym_DQUOTE,
      sym_true,
      sym_false,
      aux_sym_comment_token1,
  [1059] = 7,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_vector,
    STATE(78), 1,
      sym_squiggle,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    STATE(114), 3,
      sym__func_inner,
      sym_multifn,
      sym__fn_inner,
  [1084] = 7,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_vector,
    STATE(78), 1,
      sym_squiggle,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    STATE(134), 3,
      sym__func_inner,
      sym_multifn,
      sym__fn_inner,
  [1109] = 7,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_vector,
    STATE(78), 1,
      sym_squiggle,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    STATE(142), 3,
      sym__func_inner,
      sym_multifn,
      sym__fn_inner,
  [1134] = 7,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_vector,
    STATE(78), 1,
      sym_squiggle,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    STATE(131), 3,
      sym__func_inner,
      sym_multifn,
      sym__fn_inner,
  [1159] = 7,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_vector,
    STATE(78), 1,
      sym_squiggle,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    STATE(119), 3,
      sym__func_inner,
      sym_multifn,
      sym__fn_inner,
  [1184] = 7,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_vector,
    STATE(78), 1,
      sym_squiggle,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    STATE(116), 3,
      sym__func_inner,
      sym_multifn,
      sym__fn_inner,
  [1209] = 5,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_vector,
    STATE(91), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
    STATE(138), 2,
      sym_multifn,
      sym__fn_inner,
  [1227] = 3,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(84), 4,
      sym__cond_inner,
      sym_cond_else,
      sym_cond_branch,
      aux_sym_cond_repeat1,
  [1240] = 3,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    STATE(81), 4,
      sym__cond_inner,
      sym_cond_else,
      sym_cond_branch,
      aux_sym_cond_repeat1,
  [1253] = 3,
    ACTIONS(283), 1,
      anon_sym_LPAREN,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(81), 4,
      sym__cond_inner,
      sym_cond_else,
      sym_cond_branch,
      aux_sym_cond_repeat1,
  [1266] = 3,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    STATE(81), 4,
      sym__cond_inner,
      sym_cond_else,
      sym_cond_branch,
      aux_sym_cond_repeat1,
  [1279] = 3,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
    ACTIONS(290), 1,
      anon_sym_RPAREN,
    STATE(80), 4,
      sym__cond_inner,
      sym_cond_else,
      sym_cond_branch,
      aux_sym_cond_repeat1,
  [1292] = 3,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(81), 4,
      sym__cond_inner,
      sym_cond_else,
      sym_cond_branch,
      aux_sym_cond_repeat1,
  [1305] = 3,
    ACTIONS(277), 1,
      anon_sym_LPAREN,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
    STATE(82), 4,
      sym__cond_inner,
      sym_cond_else,
      sym_cond_branch,
      aux_sym_cond_repeat1,
  [1318] = 4,
    ACTIONS(296), 1,
      anon_sym_DQUOTE,
    ACTIONS(298), 1,
      aux_sym_string_token1,
    ACTIONS(300), 1,
      sym_string_escape,
    STATE(88), 1,
      aux_sym_string_repeat1,
  [1331] = 3,
    ACTIONS(304), 1,
      sym_ident,
    STATE(87), 1,
      aux_sym_vector_repeat1,
    ACTIONS(302), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1342] = 4,
    ACTIONS(307), 1,
      anon_sym_DQUOTE,
    ACTIONS(309), 1,
      aux_sym_string_token1,
    ACTIONS(311), 1,
      sym_string_escape,
    STATE(89), 1,
      aux_sym_string_repeat1,
  [1355] = 4,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    ACTIONS(315), 1,
      aux_sym_string_token1,
    ACTIONS(318), 1,
      sym_string_escape,
    STATE(89), 1,
      aux_sym_string_repeat1,
  [1368] = 4,
    ACTIONS(321), 1,
      anon_sym_DQUOTE,
    ACTIONS(323), 1,
      aux_sym_string_token1,
    ACTIONS(325), 1,
      sym_string_escape,
    STATE(95), 1,
      aux_sym_string_repeat1,
  [1381] = 3,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    ACTIONS(271), 1,
      anon_sym_LPAREN,
    STATE(93), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
  [1392] = 4,
    ACTIONS(309), 1,
      aux_sym_string_token1,
    ACTIONS(311), 1,
      sym_string_escape,
    ACTIONS(327), 1,
      anon_sym_DQUOTE,
    STATE(89), 1,
      aux_sym_string_repeat1,
  [1405] = 3,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    ACTIONS(329), 1,
      anon_sym_LPAREN,
    STATE(93), 2,
      sym_multifn_inner,
      aux_sym_multifn_repeat1,
  [1416] = 4,
    ACTIONS(332), 1,
      anon_sym_DQUOTE,
    ACTIONS(334), 1,
      aux_sym_string_token1,
    ACTIONS(336), 1,
      sym_string_escape,
    STATE(92), 1,
      aux_sym_string_repeat1,
  [1429] = 4,
    ACTIONS(309), 1,
      aux_sym_string_token1,
    ACTIONS(311), 1,
      sym_string_escape,
    ACTIONS(338), 1,
      anon_sym_DQUOTE,
    STATE(89), 1,
      aux_sym_string_repeat1,
  [1442] = 3,
    ACTIONS(340), 1,
      anon_sym_RBRACK,
    ACTIONS(342), 1,
      sym_ident,
    STATE(98), 1,
      aux_sym_vector_repeat1,
  [1452] = 3,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_vector,
    STATE(127), 1,
      sym__fn_inner,
  [1462] = 3,
    ACTIONS(344), 1,
      anon_sym_RBRACK,
    ACTIONS(346), 1,
      sym_ident,
    STATE(87), 1,
      aux_sym_vector_repeat1,
  [1472] = 3,
    ACTIONS(346), 1,
      sym_ident,
    ACTIONS(348), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      aux_sym_vector_repeat1,
  [1482] = 3,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_vector,
    STATE(113), 1,
      sym__fn_inner,
  [1492] = 3,
    ACTIONS(350), 1,
      anon_sym_RBRACE,
    ACTIONS(352), 1,
      sym_ident,
    STATE(99), 1,
      aux_sym_vector_repeat1,
  [1502] = 3,
    ACTIONS(273), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym_vector,
    STATE(118), 1,
      sym__fn_inner,
  [1512] = 1,
    ACTIONS(229), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1517] = 1,
    ACTIONS(354), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1522] = 1,
    ACTIONS(356), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [1527] = 1,
    ACTIONS(358), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1532] = 1,
    ACTIONS(360), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1537] = 1,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
  [1541] = 1,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
  [1545] = 1,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
  [1549] = 1,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
  [1553] = 1,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
  [1557] = 1,
    ACTIONS(362), 1,
      anon_sym_RPAREN,
  [1561] = 1,
    ACTIONS(364), 1,
      anon_sym_RPAREN,
  [1565] = 1,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
  [1569] = 1,
    ACTIONS(366), 1,
      anon_sym_RPAREN,
  [1573] = 1,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
  [1577] = 1,
    ACTIONS(368), 1,
      anon_sym_RPAREN,
  [1581] = 1,
    ACTIONS(370), 1,
      anon_sym_RPAREN,
  [1585] = 1,
    ACTIONS(372), 1,
      anon_sym_RPAREN,
  [1589] = 1,
    ACTIONS(374), 1,
      anon_sym_RPAREN,
  [1593] = 1,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
  [1597] = 1,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
  [1601] = 1,
    ACTIONS(376), 1,
      sym_ident,
  [1605] = 1,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
  [1609] = 1,
    ACTIONS(378), 1,
      sym_ident,
  [1613] = 1,
    ACTIONS(380), 1,
      anon_sym_RPAREN,
  [1617] = 1,
    ACTIONS(382), 1,
      anon_sym_RPAREN,
  [1621] = 1,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
  [1625] = 1,
    ACTIONS(384), 1,
      anon_sym_RPAREN,
  [1629] = 1,
    ACTIONS(386), 1,
      anon_sym_RPAREN,
  [1633] = 1,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
  [1637] = 1,
    ACTIONS(388), 1,
      anon_sym_RPAREN,
  [1641] = 1,
    ACTIONS(390), 1,
      anon_sym_RPAREN,
  [1645] = 1,
    ACTIONS(392), 1,
      anon_sym_RPAREN,
  [1649] = 1,
    ACTIONS(394), 1,
      anon_sym_RPAREN,
  [1653] = 1,
    ACTIONS(396), 1,
      anon_sym_RPAREN,
  [1657] = 1,
    ACTIONS(398), 1,
      anon_sym_RPAREN,
  [1661] = 1,
    ACTIONS(400), 1,
      sym_ident,
  [1665] = 1,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
  [1669] = 1,
    ACTIONS(249), 1,
      anon_sym_RPAREN,
  [1673] = 1,
    ACTIONS(402), 1,
      anon_sym_RPAREN,
  [1677] = 1,
    ACTIONS(404), 1,
      ts_builtin_sym_end,
  [1681] = 1,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
  [1685] = 1,
    ACTIONS(406), 1,
      sym_ident,
  [1689] = 1,
    ACTIONS(408), 1,
      sym_ident,
  [1693] = 1,
    ACTIONS(410), 1,
      sym_ident,
  [1697] = 1,
    ACTIONS(412), 1,
      sym_ident,
  [1701] = 1,
    ACTIONS(414), 1,
      sym_ident,
  [1705] = 1,
    ACTIONS(416), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(22)] = 0,
  [SMALL_STATE(23)] = 42,
  [SMALL_STATE(24)] = 81,
  [SMALL_STATE(25)] = 120,
  [SMALL_STATE(26)] = 159,
  [SMALL_STATE(27)] = 198,
  [SMALL_STATE(28)] = 237,
  [SMALL_STATE(29)] = 276,
  [SMALL_STATE(30)] = 315,
  [SMALL_STATE(31)] = 354,
  [SMALL_STATE(32)] = 393,
  [SMALL_STATE(33)] = 432,
  [SMALL_STATE(34)] = 471,
  [SMALL_STATE(35)] = 493,
  [SMALL_STATE(36)] = 513,
  [SMALL_STATE(37)] = 533,
  [SMALL_STATE(38)] = 551,
  [SMALL_STATE(39)] = 565,
  [SMALL_STATE(40)] = 579,
  [SMALL_STATE(41)] = 595,
  [SMALL_STATE(42)] = 611,
  [SMALL_STATE(43)] = 627,
  [SMALL_STATE(44)] = 643,
  [SMALL_STATE(45)] = 657,
  [SMALL_STATE(46)] = 673,
  [SMALL_STATE(47)] = 689,
  [SMALL_STATE(48)] = 705,
  [SMALL_STATE(49)] = 719,
  [SMALL_STATE(50)] = 735,
  [SMALL_STATE(51)] = 749,
  [SMALL_STATE(52)] = 765,
  [SMALL_STATE(53)] = 779,
  [SMALL_STATE(54)] = 795,
  [SMALL_STATE(55)] = 809,
  [SMALL_STATE(56)] = 825,
  [SMALL_STATE(57)] = 839,
  [SMALL_STATE(58)] = 855,
  [SMALL_STATE(59)] = 869,
  [SMALL_STATE(60)] = 883,
  [SMALL_STATE(61)] = 897,
  [SMALL_STATE(62)] = 913,
  [SMALL_STATE(63)] = 929,
  [SMALL_STATE(64)] = 943,
  [SMALL_STATE(65)] = 957,
  [SMALL_STATE(66)] = 971,
  [SMALL_STATE(67)] = 987,
  [SMALL_STATE(68)] = 1003,
  [SMALL_STATE(69)] = 1017,
  [SMALL_STATE(70)] = 1031,
  [SMALL_STATE(71)] = 1045,
  [SMALL_STATE(72)] = 1059,
  [SMALL_STATE(73)] = 1084,
  [SMALL_STATE(74)] = 1109,
  [SMALL_STATE(75)] = 1134,
  [SMALL_STATE(76)] = 1159,
  [SMALL_STATE(77)] = 1184,
  [SMALL_STATE(78)] = 1209,
  [SMALL_STATE(79)] = 1227,
  [SMALL_STATE(80)] = 1240,
  [SMALL_STATE(81)] = 1253,
  [SMALL_STATE(82)] = 1266,
  [SMALL_STATE(83)] = 1279,
  [SMALL_STATE(84)] = 1292,
  [SMALL_STATE(85)] = 1305,
  [SMALL_STATE(86)] = 1318,
  [SMALL_STATE(87)] = 1331,
  [SMALL_STATE(88)] = 1342,
  [SMALL_STATE(89)] = 1355,
  [SMALL_STATE(90)] = 1368,
  [SMALL_STATE(91)] = 1381,
  [SMALL_STATE(92)] = 1392,
  [SMALL_STATE(93)] = 1405,
  [SMALL_STATE(94)] = 1416,
  [SMALL_STATE(95)] = 1429,
  [SMALL_STATE(96)] = 1442,
  [SMALL_STATE(97)] = 1452,
  [SMALL_STATE(98)] = 1462,
  [SMALL_STATE(99)] = 1472,
  [SMALL_STATE(100)] = 1482,
  [SMALL_STATE(101)] = 1492,
  [SMALL_STATE(102)] = 1502,
  [SMALL_STATE(103)] = 1512,
  [SMALL_STATE(104)] = 1517,
  [SMALL_STATE(105)] = 1522,
  [SMALL_STATE(106)] = 1527,
  [SMALL_STATE(107)] = 1532,
  [SMALL_STATE(108)] = 1537,
  [SMALL_STATE(109)] = 1541,
  [SMALL_STATE(110)] = 1545,
  [SMALL_STATE(111)] = 1549,
  [SMALL_STATE(112)] = 1553,
  [SMALL_STATE(113)] = 1557,
  [SMALL_STATE(114)] = 1561,
  [SMALL_STATE(115)] = 1565,
  [SMALL_STATE(116)] = 1569,
  [SMALL_STATE(117)] = 1573,
  [SMALL_STATE(118)] = 1577,
  [SMALL_STATE(119)] = 1581,
  [SMALL_STATE(120)] = 1585,
  [SMALL_STATE(121)] = 1589,
  [SMALL_STATE(122)] = 1593,
  [SMALL_STATE(123)] = 1597,
  [SMALL_STATE(124)] = 1601,
  [SMALL_STATE(125)] = 1605,
  [SMALL_STATE(126)] = 1609,
  [SMALL_STATE(127)] = 1613,
  [SMALL_STATE(128)] = 1617,
  [SMALL_STATE(129)] = 1621,
  [SMALL_STATE(130)] = 1625,
  [SMALL_STATE(131)] = 1629,
  [SMALL_STATE(132)] = 1633,
  [SMALL_STATE(133)] = 1637,
  [SMALL_STATE(134)] = 1641,
  [SMALL_STATE(135)] = 1645,
  [SMALL_STATE(136)] = 1649,
  [SMALL_STATE(137)] = 1653,
  [SMALL_STATE(138)] = 1657,
  [SMALL_STATE(139)] = 1661,
  [SMALL_STATE(140)] = 1665,
  [SMALL_STATE(141)] = 1669,
  [SMALL_STATE(142)] = 1673,
  [SMALL_STATE(143)] = 1677,
  [SMALL_STATE(144)] = 1681,
  [SMALL_STATE(145)] = 1685,
  [SMALL_STATE(146)] = 1689,
  [SMALL_STATE(147)] = 1693,
  [SMALL_STATE(148)] = 1697,
  [SMALL_STATE(149)] = 1701,
  [SMALL_STATE(150)] = 1705,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(148),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(149),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(150),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(145),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(146),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(147),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fn_inner, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(144),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fn_inner, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(136),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multifn_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multifn_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multifn_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [196] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multifn_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multifn, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multifn, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_begin, 4, 0, 1),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_splat, 2, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_splat, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cond, 3, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_begin, 3, 0, 1),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_begin, 3, 0, 1),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 5, 0, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 2),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multifn_inner, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multifn_inner, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 5, 0, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_begin, 4, 0, 1),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defn, 5, 0, 3),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 2),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 4, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cond, 4, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond, 4, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 3, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defn, 5, 0, 3),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 5, 0, 3),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 5, 0, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [283] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cond_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cond_repeat1, 2, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [296] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [302] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 0),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [315] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [318] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [329] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multifn_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [336] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [338] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [340] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [344] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [348] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [350] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_squiggle, 2, 0, 0),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_squiggle, 3, 0, 0),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond_else, 4, 0, 0),
  [360] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cond_branch, 4, 0, 4),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [398] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__func_inner, 2, 0, 0),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [404] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_simplelisp(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
